apiVersion: v1
data:
  init.sql: "-- DB set up for Order service\r\nCREATE TABLE IF NOT EXISTS orders (\r\n
    \ id TEXT PRIMARY KEY,\r\n  customer_id TEXT NULL,\r\n  items JSONB NOT NULL,\r\n
    \ payment_method TEXT NOT NULL,\r\n  total NUMERIC(12,2) NOT NULL,\r\n  status
    TEXT NOT NULL,\r\n  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\r\n  updated_at
    TIMESTAMPTZ NOT NULL DEFAULT NOW()\r\n);\r\n\r\n-- Auto-update 'updated_at' on
    any change\r\nCREATE OR REPLACE FUNCTION update_updated_at_column()\r\nRETURNS
    TRIGGER AS $$\r\nBEGIN\r\n  NEW.updated_at = NOW();\r\n  RETURN NEW;\r\nEND;\r\n$$
    language 'plpgsql';\r\n\r\nDROP TRIGGER IF EXISTS update_order_timestamp ON orders;\r\nCREATE
    TRIGGER update_order_timestamp\r\nBEFORE UPDATE ON orders\r\nFOR EACH ROW\r\nEXECUTE
    FUNCTION update_updated_at_column();\r\n\r\n\r\n-- DB set up for Menu service\r\nCREATE
    TABLE IF NOT EXISTS menu (\r\n  id UUID PRIMARY KEY,\r\n  name TEXT NOT NULL,\r\n
    \ price NUMERIC(10,2) NOT NULL,\r\n  available BOOLEAN NOT NULL DEFAULT TRUE,\r\n
    \ created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\r\n  updated_at TIMESTAMPTZ NOT
    NULL DEFAULT NOW()\r\n);\r\n\r\nCREATE OR REPLACE FUNCTION update_menu_timestamp()\r\nRETURNS
    TRIGGER AS $$\r\nBEGIN\r\n  NEW.updated_at = NOW();\r\n  RETURN NEW;\r\nEND;\r\n$$
    LANGUAGE plpgsql;\r\n\r\nDROP TRIGGER IF EXISTS update_menu_timestamp ON menu;\r\nCREATE
    TRIGGER update_menu_timestamp\r\nBEFORE UPDATE ON menu\r\nFOR EACH ROW\r\nEXECUTE
    FUNCTION update_menu_timestamp();\r\n\r\n-- DB set up for per-day order counter
    (for IDs like YYYYMMDD-0001)\r\nCREATE TABLE IF NOT EXISTS order_counters (\r\n
    \ day_key TEXT PRIMARY KEY,\r\n  last_value INTEGER NOT NULL DEFAULT 0\r\n);\r\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: db-init
  namespace: foodtruck
