apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: foodtruck
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: sivaprasadtg/order-service:v7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: MENU_URL
              value: http://menu:3000
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: foodtruck
          readinessProbe:
            httpGet:
              path: /orders/health
              port: 4000
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /orders/health
              port: 4000
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi


---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: foodtruck
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - port: 4000
      targetPort: 4000
